name: my_presence
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.7.2
  lucide_icons: ^0.257.0
  firebase_core: ^3.11.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  easy_localization: ^3.0.7+1
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  dio: ^5.8.0+1
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  fl_chart: ^0.70.2
  google_fonts: ^6.2.1
  permission_handler: ^11.4.0
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  syncfusion_flutter_datagrid: ^28.2.9
  multi_dropdown: ^3.0.1
  drop_down_list: ^2.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  intl: ^0.19.0
  crypto: ^3.0.6
  http: ^1.3.0
  jwt_decode: ^0.3.1
  pointycastle: ^4.0.0
  basic_utils: ^5.8.2
  googleapis_auth: ^1.6.0
  googleapis: ^14.0.0
  timezone: ^0.10.0
  uuid: ^4.5.1
  bloc_concurrency: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3


flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/fonts/
